[package]
name = "self-balancing-binary-serach-tree"
version = "0.1.0"
authors = ["KoyamaSohei <skoyama@hpcs.hpcc.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
assert-str = "0.1"